# USB device identification
CONFIG_USB_DEVICE_PRODUCT="Cygnus"
# you can also set manufacturer/vendor IDs if desired
# CONFIG_USB_DEVICE_MANUFACTURER="Your Name"
# CONFIG_USB_DEVICE_VENDOR_ID=0xFEED
# CONFIG_USB_DEVICE_PRODUCT_ID=0x6060

# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_KEYBOARD_NAME="Cygnus"

# enable the module and pick a layout
CONFIG_PROSPECTOR_STATUS_SCREEN_CLASSIC=y   # or RADII / FIELD / OPERATOR

# optional tweaks
# CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=y
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=n 
